In [1]:
import pickle
import pandas as pd
from tabulate import tabulate
import numpy as np
import pandas as pd

In [2]:

#mètriques de tots els partis (llista de diccionaris)
Barcelona = "../Data/Team1/04Stage/playersList.pkl"
RayoVallecano = "../Data/Team2/04Stage/playersList.pkl"

In [3]:
def loadPlayersList(playersList):
    try:
        with open(playersList, 'rb') as file:
            # Load data from the file
            playersListData = pickle.load(file)
        return playersListData
    except FileNotFoundError:
        print("File not found:", playersList)
        return None
    except Exception as e:
        print("An error occurred while loading the players list:", str(e))
        return None

In [4]:
def loadPlayersDataFrame(playersDict):
    try:
        players_df = pd.DataFrame(list(playersDict.items()), columns=['Player ID', 'Player Name'])
        players_df.reset_index(drop=True, inplace=True)
        return players_df
    except Exception as e:
        print("An error occurred while loading the players DataFrame:", str(e))
        return None

FCBARCELONA

In [5]:
barcelonaPlayersList = loadPlayersList(Barcelona)

In [6]:
print(barcelonaPlayersList)

{4320: 'Neymar da Silva Santos Junior', 5506: 'Javier Alejandro Mascherano', 4324: 'Daniel Alves da Silva', 6379: 'Sergi Roberto Carnicer', 5203: 'Sergio Busquets i Burgos', 4691: 'Claudio Andrés Bravo Muñoz', 11094: 'Arda Turan', 6998: 'Rafael Alcântara do Nascimento', 6616: 'Munir El Haddadi Mohamed', 5213: 'Gerard Piqué Bernabéu', 5503: 'Lionel Andrés Messi Cuccittini', 5216: 'Andrés Iniesta Luján', 5211: 'Jordi Alba Ramos', 5470: 'Ivan Rakitić', 5246: 'Luis Alberto Suárez Díaz', 7068: 'Marc Bartra Aregall', 22102: 'Adriano Correia Claro', 20055: 'Marc-André ter Stegen', 10609: 'Jérémy Mathieu', 6400: 'Aleix Vidal Parreu', 6332: 'Thomas Vermaelen', 3508: 'Sandro Ramírez Castillo', 6834: 'Gerard Gumbau Garriga', 27318: 'Douglas Pereira dos Santos', 21229: 'Sergi Samper Montaña'}

In [7]:
barcelonaPlayersTable = loadPlayersDataFrame(barcelonaPlayersList)

In [8]:
barcelonaPlayersTable

    Player ID                     Player Name
0        4320   Neymar da Silva Santos Junior
1        5506     Javier Alejandro Mascherano
2        4324           Daniel Alves da Silva
3        6379          Sergi Roberto Carnicer
4        5203        Sergio Busquets i Burgos
5        4691      Claudio Andrés Bravo Muñoz
6       11094                      Arda Turan
7        6998  Rafael Alcântara do Nascimento
8        6616        Munir El Haddadi Mohamed
9        5213           Gerard Piqué Bernabéu
10       5503  Lionel Andrés Messi Cuccittini
11       5216            Andrés Iniesta Luján
12       5211                Jordi Alba Ramos
13       5470                    Ivan Rakitić
14       5246        Luis Alberto Suárez Díaz
15       7068             Marc Bartra Aregall
16      22102           Adriano Correia Claro
17      20055           Marc-André ter Stegen
18      10609                  Jérémy Mathieu
19       6400              Aleix Vidal Parreu
20       6332                Thomas Vermaelen
21       3508         Sandro Ramírez Castillo
22       6834           Gerard Gumbau Garriga
23      27318      Douglas Pereira dos Santos
24      21229            Sergi Samper Montaña

RAYO VALLECANO

In [9]:
vallecanoPlayersList = loadPlayersList(RayoVallecano)

In [10]:
print(vallecanoPlayersList)

{26848: 'Roberto Trashorras Gayoso', 11298: 'José Ignacio Martínez García', 18404: 'José Ángel Crespo Rincón', 4711: 'Pablo Hernández Domínguez', 24138: 'Joaquín José Marín Ruiz', 26222: 'José Eduardo Rosa Vale de Castro', 26607: 'José Raúl Baena Urdiales', 11542: 'Javier Guerra Rodríguez', 7900: 'Tiago Manuel Dias Correia', 26685: 'Nicolás Ladislao Fedor Flores', 24255: 'Juan Carlos Martín Corral', 26690: 'Alberto Mateus Contreiras Gonçalves', 11539: 'Adrián Embarba Blázquez', 6713: 'Diego Javier Llorente Ríos', 6914: 'Roberto Román Triguero', 27144: 'Antonio Amaya Carazo', 6852: 'Jozabed Sánchez Ruiz', 6743: 'Manuel Rolando Iturra Urrutia', 10727: 'Răzvan Dincă Raț', 26797: 'Francisco Medina Luna', 24782: 'Jonhatan Montiel Caballero', 10612: 'Yoel Rodríguez Oterino', 23761: 'Alhassane Bangoura', 11146: 'Luis Carlos Fariña Olivera', 26070: 'Antonio Rodríguez Martínez', 9246: 'Patrick Ebert', 11543: 'José Antonio Dorado Ramírez', 43354: 'Chengdong Zhang', 16073: 'Aras Özbiliz'}

In [11]:
RVallecanoPlayersTable = loadPlayersDataFrame(vallecanoPlayersList)

In [12]:
RVallecanoPlayersTable

    Player ID                          Player Name
0       26848            Roberto Trashorras Gayoso
1       11298         José Ignacio Martínez García
2       18404             José Ángel Crespo Rincón
3        4711            Pablo Hernández Domínguez
4       24138              Joaquín José Marín Ruiz
5       26222     José Eduardo Rosa Vale de Castro
6       26607             José Raúl Baena Urdiales
7       11542              Javier Guerra Rodríguez
8        7900            Tiago Manuel Dias Correia
9       26685        Nicolás Ladislao Fedor Flores
10      24255            Juan Carlos Martín Corral
11      26690  Alberto Mateus Contreiras Gonçalves
12      11539              Adrián Embarba Blázquez
13       6713           Diego Javier Llorente Ríos
14       6914               Roberto Román Triguero
15      27144                 Antonio Amaya Carazo
16       6852                 Jozabed Sánchez Ruiz
17       6743        Manuel Rolando Iturra Urrutia
18      10727                     Răzvan Dincă Raț
19      26797                Francisco Medina Luna
20      24782           Jonhatan Montiel Caballero
21      10612               Yoel Rodríguez Oterino
22      23761                   Alhassane Bangoura
23      11146           Luis Carlos Fariña Olivera
24      26070           Antonio Rodríguez Martínez
25       9246                        Patrick Ebert
26      11543          José Antonio Dorado Ramírez
27      43354                      Chengdong Zhang
28      16073                         Aras Özbiliz