In [21]:
import pickle
from tabulate import tabulate

In [22]:
path = "../Data/Team_2/06Stage/Tables/Score/Global/globalMetrics.pkl"

In [23]:
def loadPickleFile(file):
    try:
        with open(file, "rb") as f:
            deserializedFile = pickle.load(f)
        return deserializedFile
    except FileNotFoundError:
        print(f"File  not found.")

In [24]:
table = loadPickleFile(path)
table

    av_clust               dty              diam
        Mean   Std Count  Mean   Std Count  Mean   Std Count
0_1     0.48  0.22    19  0.45  0.19    19  3.54  1.56  13.0
1_0     0.48  0.17    18  0.41  0.17    18  3.21  0.70  14.0
1_1     0.50  0.22    15  0.46  0.17    15  3.00  0.63  11.0
2_1     0.48  0.23     9  0.42  0.20     9  3.17  0.75   6.0
2_0     0.48  0.23     8  0.42  0.20     8  3.00  0.82   4.0
2_2     0.39  0.19    10  0.34  0.14    10  3.17  0.41   6.0
2_3     0.30  0.26     3  0.34  0.10     3  0.00  0.00   0.0
0_2     0.47  0.29    10  0.45  0.21    10  3.12  0.99   8.0
1_2     0.37  0.21    11  0.32  0.10    11  4.00  1.73   3.0
3_1     0.47  0.00     1  0.47  0.00     1  3.00  0.00   1.0
3_0     0.17  0.24     2  0.30  0.04     2  0.00  0.00   0.0
0_3     0.65  0.05     3  0.62  0.06     3  2.33  0.58   3.0
1_3     0.54  0.33     3  0.54  0.26     3  2.50  0.71   2.0
1_4     0.07  0.10     2  0.22  0.05     2  0.00  0.00   0.0
1_5     0.24  0.01     2  0.26  0.01     2  4.50  0.71   2.0
2_5     0.51  0.14     2  0.50  0.12     2  2.50  0.71   2.0